changelog:
  exclude:
    labels:
      - skip-release-notes
      - ignore-for-release
    authors:
      - dependabot
      - github-actions
  categories:
    - title: Features
      labels:
        - feat
        - feature
    - title: Bug Fixes
      labels:
        - fix
        - bug
    - title: Performance
      labels:
        - perf
    - title: Refactors
      labels:
        - refactor
    - title: Build
      labels:
        - build
    - title: CI
      labels:
        - ci
    - title: Documentation
      labels:
        - docs
    - title: Other Changes
      labels:
        - "*"
