/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TmuxRouteImport } from './routes/tmux'
import { Route as OpsRouteImport } from './routes/ops'
import { Route as IndexRouteImport } from './routes/index'

const TmuxRoute = TmuxRouteImport.update({
  id: '/tmux',
  path: '/tmux',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsRoute = OpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ops': typeof OpsRoute
  '/tmux': typeof TmuxRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ops': typeof OpsRoute
  '/tmux': typeof TmuxRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ops': typeof OpsRoute
  '/tmux': typeof TmuxRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ops' | '/tmux'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ops' | '/tmux'
  id: '__root__' | '/' | '/ops' | '/tmux'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OpsRoute: typeof OpsRoute
  TmuxRoute: typeof TmuxRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tmux': {
      id: '/tmux'
      path: '/tmux'
      fullPath: '/tmux'
      preLoaderRoute: typeof TmuxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops': {
      id: '/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof OpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OpsRoute: OpsRoute,
  TmuxRoute: TmuxRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
