/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TmuxRouteImport } from './routes/tmux'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as RunbooksRouteImport } from './routes/runbooks'
import { Route as OpsRouteImport } from './routes/ops'
import { Route as MetricsRouteImport } from './routes/metrics'
import { Route as GuardrailsRouteImport } from './routes/guardrails'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as ActivitiesRouteImport } from './routes/activities'
import { Route as IndexRouteImport } from './routes/index'

const TmuxRoute = TmuxRouteImport.update({
  id: '/tmux',
  path: '/tmux',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const RunbooksRoute = RunbooksRouteImport.update({
  id: '/runbooks',
  path: '/runbooks',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsRoute = OpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricsRoute = MetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardrailsRoute = GuardrailsRouteImport.update({
  id: '/guardrails',
  path: '/guardrails',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesRoute = ActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/alerts': typeof AlertsRoute
  '/guardrails': typeof GuardrailsRoute
  '/metrics': typeof MetricsRoute
  '/ops': typeof OpsRoute
  '/runbooks': typeof RunbooksRoute
  '/services': typeof ServicesRoute
  '/tmux': typeof TmuxRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/alerts': typeof AlertsRoute
  '/guardrails': typeof GuardrailsRoute
  '/metrics': typeof MetricsRoute
  '/ops': typeof OpsRoute
  '/runbooks': typeof RunbooksRoute
  '/services': typeof ServicesRoute
  '/tmux': typeof TmuxRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/alerts': typeof AlertsRoute
  '/guardrails': typeof GuardrailsRoute
  '/metrics': typeof MetricsRoute
  '/ops': typeof OpsRoute
  '/runbooks': typeof RunbooksRoute
  '/services': typeof ServicesRoute
  '/tmux': typeof TmuxRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activities'
    | '/alerts'
    | '/guardrails'
    | '/metrics'
    | '/ops'
    | '/runbooks'
    | '/services'
    | '/tmux'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activities'
    | '/alerts'
    | '/guardrails'
    | '/metrics'
    | '/ops'
    | '/runbooks'
    | '/services'
    | '/tmux'
  id:
    | '__root__'
    | '/'
    | '/activities'
    | '/alerts'
    | '/guardrails'
    | '/metrics'
    | '/ops'
    | '/runbooks'
    | '/services'
    | '/tmux'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivitiesRoute: typeof ActivitiesRoute
  AlertsRoute: typeof AlertsRoute
  GuardrailsRoute: typeof GuardrailsRoute
  MetricsRoute: typeof MetricsRoute
  OpsRoute: typeof OpsRoute
  RunbooksRoute: typeof RunbooksRoute
  ServicesRoute: typeof ServicesRoute
  TmuxRoute: typeof TmuxRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tmux': {
      id: '/tmux'
      path: '/tmux'
      fullPath: '/tmux'
      preLoaderRoute: typeof TmuxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runbooks': {
      id: '/runbooks'
      path: '/runbooks'
      fullPath: '/runbooks'
      preLoaderRoute: typeof RunbooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops': {
      id: '/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof OpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metrics': {
      id: '/metrics'
      path: '/metrics'
      fullPath: '/metrics'
      preLoaderRoute: typeof MetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guardrails': {
      id: '/guardrails'
      path: '/guardrails'
      fullPath: '/guardrails'
      preLoaderRoute: typeof GuardrailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities': {
      id: '/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof ActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivitiesRoute: ActivitiesRoute,
  AlertsRoute: AlertsRoute,
  GuardrailsRoute: GuardrailsRoute,
  MetricsRoute: MetricsRoute,
  OpsRoute: OpsRoute,
  RunbooksRoute: RunbooksRoute,
  ServicesRoute: ServicesRoute,
  TmuxRoute: TmuxRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
