name: Bug report
description: Report a reproducible problem in Sentinel
title: "[bug] "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Please provide enough detail to reproduce the issue. Include logs and steps whenever possible.

  - type: input
    id: summary
    attributes:
      label: Summary
      description: Short description of the bug
      placeholder: Terminal disconnects after resizing browser window
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Provide exact steps
      placeholder: |
        1. Start Sentinel with `make run`
        2. Open /tmux
        3. Attach to a session
        4. Resize browser window
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: Terminal should remain connected and resize correctly.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      placeholder: Terminal disconnects and shows websocket error.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs or screenshots
      description: Paste relevant logs, stack traces, or screenshots
      render: shell

  - type: input
    id: sentinel_version
    attributes:
      label: Sentinel version
      placeholder: v0.1.0 or commit SHA
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: OS
      placeholder: Ubuntu 24.04 / macOS 15.0
    validations:
      required: true

  - type: input
    id: browser
    attributes:
      label: Browser
      placeholder: Chrome 132 / Firefox 133 / Safari 18
    validations:
      required: true

  - type: input
    id: tmux_version
    attributes:
      label: tmux version
      placeholder: tmux 3.4

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I searched existing issues and did not find a duplicate.
          required: true
        - label: I can reproduce this on the latest `main` branch.
          required: false
