# fish completion for sentinel
# Generated by `sentinel completion fish`.

complete -c sentinel -f

# ── Top-level commands ───────────────────────────────────────────────
complete -c sentinel -n __fish_use_subcommand -a serve -d 'Start the HTTP server'
complete -c sentinel -n __fish_use_subcommand -a service -d 'Manage the local service'
complete -c sentinel -n __fish_use_subcommand -a doctor -d 'Check the local environment'
complete -c sentinel -n __fish_use_subcommand -a update -d 'Check or apply binary updates'
complete -c sentinel -n __fish_use_subcommand -a completion -d 'Print a shell completion script'
complete -c sentinel -n __fish_use_subcommand -a version -d 'Print the version'
complete -c sentinel -n __fish_use_subcommand -a help -d 'Show help'

# ── service ──────────────────────────────────────────────────────────
complete -c sentinel -n '__fish_seen_subcommand_from service; and not __fish_seen_subcommand_from install uninstall status logs autoupdate' \
    -a 'install uninstall status logs autoupdate'
complete -c sentinel -n '__fish_seen_subcommand_from autoupdate; and not __fish_seen_subcommand_from install uninstall status' \
    -a 'install uninstall status'

# ── update ───────────────────────────────────────────────────────────
complete -c sentinel -n '__fish_seen_subcommand_from update; and not __fish_seen_subcommand_from check apply status' \
    -a 'check apply status'

# ── completion ───────────────────────────────────────────────────────
complete -c sentinel -n '__fish_seen_subcommand_from completion; and not __fish_seen_subcommand_from bash zsh fish' \
    -a 'bash zsh fish'

# ── flags ────────────────────────────────────────────────────────────
complete -c sentinel -l help -d 'Show help'

# service install / autoupdate install
complete -c sentinel -n '__fish_seen_subcommand_from install' -l exec -r -d 'Binary path for ExecStart'
complete -c sentinel -n '__fish_seen_subcommand_from install' -l enable -d 'Enable at startup'
complete -c sentinel -n '__fish_seen_subcommand_from install' -l start -d 'Start now'
# service uninstall / autoupdate uninstall
complete -c sentinel -n '__fish_seen_subcommand_from uninstall' -l disable -d 'Disable auto-start'
complete -c sentinel -n '__fish_seen_subcommand_from uninstall' -l stop -d 'Stop the service'
complete -c sentinel -n '__fish_seen_subcommand_from uninstall' -l remove-unit -d 'Remove the unit file'
# service logs
complete -c sentinel -n '__fish_seen_subcommand_from logs' -s f -l follow -d 'Stream new log lines'
complete -c sentinel -n '__fish_seen_subcommand_from logs' -s n -l lines -r -d 'Number of past lines'
# autoupdate
complete -c sentinel -n '__fish_seen_subcommand_from autoupdate' -l service -r -d 'Service unit to restart'
complete -c sentinel -n '__fish_seen_subcommand_from autoupdate' -l on-calendar -x -a 'daily hourly weekly' -d 'Update schedule'
complete -c sentinel -n '__fish_seen_subcommand_from autoupdate' -l randomized-delay -r -d 'Randomized delay'
# update check / apply
complete -c sentinel -n '__fish_seen_subcommand_from check apply' -l repo -r -d 'GitHub repository'
complete -c sentinel -n '__fish_seen_subcommand_from check apply' -l api -r -d 'GitHub API base URL'
complete -c sentinel -n '__fish_seen_subcommand_from check apply' -l os -r -d 'Target OS'
complete -c sentinel -n '__fish_seen_subcommand_from check apply' -l arch -r -d 'Target CPU architecture'
complete -c sentinel -n '__fish_seen_subcommand_from apply' -l allow-downgrade -d 'Allow installing an older release'
complete -c sentinel -n '__fish_seen_subcommand_from apply' -l allow-unverified -d 'Allow update without checksum'
complete -c sentinel -n '__fish_seen_subcommand_from apply' -l restart -d 'Restart the service after update'
# --scope (autoupdate + update apply)
complete -c sentinel -n '__fish_seen_subcommand_from autoupdate apply' -l scope -x -a 'auto user system launchd none' -d 'Manager scope'
