/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MetricsRouteImport } from './routes/metrics'
import { Route as OpsRouteImport } from './routes/ops'
import { Route as RunbooksRouteImport } from './routes/runbooks'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TmuxRouteImport } from './routes/tmux'
import { Route as MaintenanceStorageRouteImport } from './routes/maintenance.storage'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as SettingsSectionRouteImport } from './routes/settings.$section'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricsRoute = MetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsRoute = OpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const RunbooksRoute = RunbooksRouteImport.update({
  id: '/runbooks',
  path: '/runbooks',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TmuxRoute = TmuxRouteImport.update({
  id: '/tmux',
  path: '/tmux',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceStorageRoute = MaintenanceStorageRouteImport.update({
  id: '/maintenance/storage',
  path: '/maintenance/storage',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSectionRoute = SettingsSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => SettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/metrics': typeof MetricsRoute
  '/ops': typeof OpsRoute
  '/runbooks': typeof RunbooksRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRouteWithChildren
  '/tmux': typeof TmuxRoute
  '/maintenance/storage': typeof MaintenanceStorageRoute
  '/settings/$section': typeof SettingsSectionRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/metrics': typeof MetricsRoute
  '/ops': typeof OpsRoute
  '/runbooks': typeof RunbooksRoute
  '/services': typeof ServicesRoute
  '/tmux': typeof TmuxRoute
  '/maintenance/storage': typeof MaintenanceStorageRoute
  '/settings/$section': typeof SettingsSectionRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/metrics': typeof MetricsRoute
  '/ops': typeof OpsRoute
  '/runbooks': typeof RunbooksRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRouteWithChildren
  '/tmux': typeof TmuxRoute
  '/maintenance/storage': typeof MaintenanceStorageRoute
  '/settings/$section': typeof SettingsSectionRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/metrics'
    | '/ops'
    | '/runbooks'
    | '/services'
    | '/settings'
    | '/tmux'
    | '/maintenance/storage'
    | '/settings/$section'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/metrics'
    | '/ops'
    | '/runbooks'
    | '/services'
    | '/tmux'
    | '/maintenance/storage'
    | '/settings/$section'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/metrics'
    | '/ops'
    | '/runbooks'
    | '/services'
    | '/settings'
    | '/tmux'
    | '/maintenance/storage'
    | '/settings/$section'
    | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MetricsRoute: typeof MetricsRoute
  OpsRoute: typeof OpsRoute
  RunbooksRoute: typeof RunbooksRoute
  ServicesRoute: typeof ServicesRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  TmuxRoute: typeof TmuxRoute
  MaintenanceStorageRoute: typeof MaintenanceStorageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metrics': {
      id: '/metrics'
      path: '/metrics'
      fullPath: '/metrics'
      preLoaderRoute: typeof MetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops': {
      id: '/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof OpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runbooks': {
      id: '/runbooks'
      path: '/runbooks'
      fullPath: '/runbooks'
      preLoaderRoute: typeof RunbooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tmux': {
      id: '/tmux'
      path: '/tmux'
      fullPath: '/tmux'
      preLoaderRoute: typeof TmuxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance/storage': {
      id: '/maintenance/storage'
      path: '/maintenance/storage'
      fullPath: '/maintenance/storage'
      preLoaderRoute: typeof MaintenanceStorageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/$section': {
      id: '/settings/$section'
      path: '/$section'
      fullPath: '/settings/$section'
      preLoaderRoute: typeof SettingsSectionRouteImport
      parentRoute: typeof SettingsRoute
    }
  }
}

interface SettingsRouteChildren {
  SettingsSectionRoute: typeof SettingsSectionRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsSectionRoute: SettingsSectionRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MetricsRoute: MetricsRoute,
  OpsRoute: OpsRoute,
  RunbooksRoute: RunbooksRoute,
  ServicesRoute: ServicesRoute,
  SettingsRoute: SettingsRouteWithChildren,
  TmuxRoute: TmuxRoute,
  MaintenanceStorageRoute: MaintenanceStorageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
