/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MetricsRouteImport } from './routes/metrics'
import { Route as OpsRouteImport } from './routes/ops'
import { Route as RunbooksRouteImport } from './routes/runbooks'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as TmuxRouteImport } from './routes/tmux'
import { Route as MaintenanceStorageRouteImport } from './routes/maintenance.storage'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricsRoute = MetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsRoute = OpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const RunbooksRoute = RunbooksRouteImport.update({
  id: '/runbooks',
  path: '/runbooks',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const TmuxRoute = TmuxRouteImport.update({
  id: '/tmux',
  path: '/tmux',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceStorageRoute = MaintenanceStorageRouteImport.update({
  id: '/maintenance/storage',
  path: '/maintenance/storage',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/metrics': typeof MetricsRoute
  '/ops': typeof OpsRoute
  '/runbooks': typeof RunbooksRoute
  '/services': typeof ServicesRoute
  '/tmux': typeof TmuxRoute
  '/maintenance/storage': typeof MaintenanceStorageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/metrics': typeof MetricsRoute
  '/ops': typeof OpsRoute
  '/runbooks': typeof RunbooksRoute
  '/services': typeof ServicesRoute
  '/tmux': typeof TmuxRoute
  '/maintenance/storage': typeof MaintenanceStorageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/metrics': typeof MetricsRoute
  '/ops': typeof OpsRoute
  '/runbooks': typeof RunbooksRoute
  '/services': typeof ServicesRoute
  '/tmux': typeof TmuxRoute
  '/maintenance/storage': typeof MaintenanceStorageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/metrics'
    | '/ops'
    | '/runbooks'
    | '/services'
    | '/tmux'
    | '/maintenance/storage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/metrics'
    | '/ops'
    | '/runbooks'
    | '/services'
    | '/tmux'
    | '/maintenance/storage'
  id:
    | '__root__'
    | '/'
    | '/metrics'
    | '/ops'
    | '/runbooks'
    | '/services'
    | '/tmux'
    | '/maintenance/storage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MetricsRoute: typeof MetricsRoute
  OpsRoute: typeof OpsRoute
  RunbooksRoute: typeof RunbooksRoute
  ServicesRoute: typeof ServicesRoute
  TmuxRoute: typeof TmuxRoute
  MaintenanceStorageRoute: typeof MaintenanceStorageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metrics': {
      id: '/metrics'
      path: '/metrics'
      fullPath: '/metrics'
      preLoaderRoute: typeof MetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops': {
      id: '/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof OpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runbooks': {
      id: '/runbooks'
      path: '/runbooks'
      fullPath: '/runbooks'
      preLoaderRoute: typeof RunbooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tmux': {
      id: '/tmux'
      path: '/tmux'
      fullPath: '/tmux'
      preLoaderRoute: typeof TmuxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance/storage': {
      id: '/maintenance/storage'
      path: '/maintenance/storage'
      fullPath: '/maintenance/storage'
      preLoaderRoute: typeof MaintenanceStorageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MetricsRoute: MetricsRoute,
  OpsRoute: OpsRoute,
  RunbooksRoute: RunbooksRoute,
  ServicesRoute: ServicesRoute,
  TmuxRoute: TmuxRoute,
  MaintenanceStorageRoute: MaintenanceStorageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
