import { useState } from 'react'
import { CircleHelp } from 'lucide-react'
import { Button } from '@/components/ui/button'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog'
import { TooltipHelper } from '@/components/TooltipHelper'

export default function TimelineHelpDialog() {
  const [open, setOpen] = useState(false)

  return (
    <>
      <TooltipHelper content="About Timeline">
        <Button
          variant="ghost"
          size="icon"
          className="cursor-pointer border border-border bg-surface-hover text-secondary-foreground hover:bg-accent hover:text-foreground"
          onClick={() => setOpen(true)}
          aria-label="About Timeline"
        >
          <CircleHelp className="h-4 w-4" />
        </Button>
      </TooltipHelper>
      <Dialog open={open} onOpenChange={setOpen}>
        <DialogContent className="sm:max-w-lg">
          <DialogHeader>
            <DialogTitle>About Timeline</DialogTitle>
            <DialogDescription>
              How the Sentinel operations timeline works.
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-4 text-sm leading-relaxed text-muted-foreground">
            <section>
              <h3 className="mb-1 font-medium text-foreground">Audit Log</h3>
              <p>
                The timeline is an append-only audit log that records every
                significant operation performed through Sentinel.
              </p>
            </section>
            <section>
              <h3 className="mb-1 font-medium text-foreground">Sources</h3>
              <p>
                Events are generated by service actions (start, stop, restart),
                alert acknowledgements, runbook executions, and other control
                plane operations.
              </p>
            </section>
            <section>
              <h3 className="mb-1 font-medium text-foreground">Filtering</h3>
              <p>
                Use the search field to filter events by text content, or narrow
                by severity level (info, warn, error) to focus on specific event
                types.
              </p>
            </section>
            <section>
              <h3 className="mb-1 font-medium text-foreground">Retention</h3>
              <p>
                Timeline events are stored locally in the Sentinel database.
                They persist across restarts and are scoped to this Sentinel
                instance.
              </p>
            </section>
          </div>
        </DialogContent>
      </Dialog>
    </>
  )
}
