#compdef sentinel
# zsh completion for sentinel
# Generated by `sentinel completion zsh`.

_sentinel() {
    local -a path_words opts
    local w
    integer i

    # Resolve the command path, skipping flags.
    for ((i = 2; i < CURRENT; i++)); do
        w="${words[i]}"
        [[ "$w" == -* ]] && continue
        path_words+=("$w")
    done

    local cmd="${path_words[1]}"
    local sub="${path_words[2]}"
    local subsub="${path_words[3]}"

    case "$cmd" in
        '') opts=(daemon service doctor update completion version help) ;;
        daemon | doctor) opts=(--help) ;;
        completion) opts=(bash zsh fish) ;;
        service)
            case "$sub" in
                '') opts=(install uninstall status logs autoupdate) ;;
                install) opts=(--exec --enable --start --help) ;;
                uninstall) opts=(--disable --stop --remove-unit --help) ;;
                status) opts=(--help) ;;
                logs) opts=(--follow --lines --help) ;;
                autoupdate)
                    case "$subsub" in
                        '') opts=(install uninstall status) ;;
                        install) opts=(--exec --enable --start --service --scope --on-calendar --randomized-delay --help) ;;
                        uninstall) opts=(--disable --stop --remove-unit --scope --help) ;;
                        status) opts=(--scope --help) ;;
                    esac
                    ;;
            esac
            ;;
        update)
            case "$sub" in
                '') opts=(check apply status) ;;
                check) opts=(--repo --api --os --arch --help) ;;
                apply) opts=(--repo --api --os --arch --exec --allow-downgrade --allow-unverified --restart --service --scope --help) ;;
                status) opts=(--help) ;;
            esac
            ;;
    esac

    compadd -a opts
}

if [ "$funcstack[1]" = "_sentinel" ]; then
    _sentinel
else
    compdef _sentinel sentinel
fi
