# bash completion for sentinel
# Generated by `sentinel completion bash`.

_sentinel() {
    local cur prev cmd sub subsub i w opts
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD - 1]}"

    # Value completion for enum-style flags.
    case "$prev" in
        --scope)
            COMPREPLY=($(compgen -W "auto user system launchd none" -- "$cur"))
            return
            ;;
        --on-calendar)
            COMPREPLY=($(compgen -W "daily hourly weekly" -- "$cur"))
            return
            ;;
    esac

    # Resolve the command path, skipping flags.
    cmd=""
    sub=""
    subsub=""
    for ((i = 1; i < COMP_CWORD; i++)); do
        w="${COMP_WORDS[i]}"
        case "$w" in
            -*) continue ;;
        esac
        if [[ -z $cmd ]]; then
            cmd="$w"
        elif [[ -z $sub ]]; then
            sub="$w"
        elif [[ -z $subsub ]]; then
            subsub="$w"
        fi
    done

    opts=""
    case "$cmd" in
        "")
            opts="serve service doctor update completion version help --version --help"
            ;;
        serve | doctor)
            opts="--help"
            ;;
        completion)
            opts="bash zsh fish --help"
            ;;
        service)
            case "$sub" in
                "") opts="install uninstall status logs autoupdate" ;;
                install) opts="--exec --enable --start --help" ;;
                uninstall) opts="--disable --stop --remove-unit --help" ;;
                status) opts="--help" ;;
                logs) opts="--follow --lines --help" ;;
                autoupdate)
                    case "$subsub" in
                        "") opts="install uninstall status" ;;
                        install) opts="--exec --enable --start --service --scope --on-calendar --randomized-delay --help" ;;
                        uninstall) opts="--disable --stop --remove-unit --scope --help" ;;
                        status) opts="--scope --help" ;;
                    esac
                    ;;
            esac
            ;;
        update)
            case "$sub" in
                "") opts="check apply status" ;;
                check) opts="--repo --api --os --arch --help" ;;
                apply) opts="--repo --api --os --arch --exec --allow-downgrade --allow-unverified --restart --service --scope --help" ;;
                status) opts="--help" ;;
            esac
            ;;
    esac

    COMPREPLY=($(compgen -W "$opts" -- "$cur"))
}

complete -F _sentinel sentinel
