name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ci:
    uses: opus-domini/actions/.github/workflows/ci.yml@372c1c178b6721176b31b9cb61e09dd3a7714383
    with:
      frontend: true
      upload-codecov: true
