name: CI

on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - .github/.release-please-manifest.json
      - CHANGELOG.md
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ci:
    uses: opus-domini/actions/.github/workflows/ci.yml@4e7235e2cca5901e246d5ab57084d6556be76c0a
    with:
      frontend: true
      upload-codecov: true
