name: CI

on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - .github/.release-please-manifest.json
      - CHANGELOG.md
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ci:
    uses: opus-domini/actions/.github/workflows/ci.yml@9a41fa5fbbd6bc092388077cfaf533af7a6458fc
    with:
      frontend: true
      upload-codecov: true
