name: Release Please

on:
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
      id-token: write
      issues: write
      pull-requests: write
    uses: opus-domini/actions/.github/workflows/release.yml@08fc4c4e801f551ee1c960b7645d4c56127793e2
    with:
      frontend: true
