name: Prepare Release PR

on:
  push:
    branches:
      - main

jobs:
  prepare:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    uses: opus-domini/actions/.github/workflows/release-pr.yml@d46c516d62240b7b6a10bb3e4caf2a1810e8d8a9
