name: Prepare Release PR

on:
  push:
    branches:
      - main

jobs:
  prepare:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    uses: opus-domini/actions/.github/workflows/release-pr.yml@9a41fa5fbbd6bc092388077cfaf533af7a6458fc
