name: Release Please

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
      id-token: write
      issues: write
      pull-requests: write
    uses: opus-domini/actions/.github/workflows/release.yml@372c1c178b6721176b31b9cb61e09dd3a7714383
    with:
      frontend: true
