name: Publish Release

on:
  pull_request:
    types:
      - closed
    branches:
      - main
    paths:
      - .github/.release-please-manifest.json

jobs:
  publish:
    if: >-
      ${{ github.event.action == 'closed' &&
          github.event.pull_request.merged == true &&
          github.event.pull_request.base.ref == 'main' &&
          github.event.pull_request.base.repo.full_name == github.repository &&
          github.event.pull_request.head.repo.full_name == github.repository &&
          startsWith(github.event.pull_request.head.ref, 'release-please--branches--main') &&
          contains(github.event.pull_request.labels.*.name, 'autorelease: pending') }}
    permissions:
      contents: write
      id-token: write
      issues: write
      pull-requests: write
    uses: opus-domini/actions/.github/workflows/release.yml@d46c516d62240b7b6a10bb3e4caf2a1810e8d8a9
    with:
      frontend: true
