name: Release Please

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
      id-token: write
      issues: write
      pull-requests: write
    uses: opus-domini/actions/.github/workflows/release.yml@e61ccf4381caa98150bdc8bd8d9ea791235a6691
    with:
      frontend: true
