name: Prepare Release PR

on:
  push:
    branches:
      - main

jobs:
  prepare:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    uses: opus-domini/actions/.github/workflows/release-pr.yml@b5a8d4143e39e1235287da0185b10fbfbdf5613a
